require_relative 'command'
require_relative 'delete'
require_relative 'go_to_dir'
require_relative 'list_dir'
require_relative 'make_dir'
require_relative 'remove_dir'
require_relative 'get_file'
require_relative 'put_file'
